export const FETCH_EACCC_SUCCESS = 'FETCH_EACCC_SUCCESS';
export const FETCH_EACCC_REQUEST = 'FETCH_EACCC_REQUEST';
export const FETCH_EACCC_FAILURE = 'FETCH_EACCC_FAILURE';

export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_SINGLE_EVENT_SUCCESS = 'FETCH_SINGLE_EVENT_SUCCESS';
export const FETCH_SINGLE_EVENT_REQUEST = 'FETCH_SINGLE_EVENT_REQUEST';
export const FETCH_SINGLE_EVENT_FAILURE = 'FETCH_SINGLE_EVENT_FAILURE';

export const FETCH_EVENT_TYPE_SUCCESS = 'FETCH_EVENT_TYPE_SUCCESS';
export const FETCH_EVENT_TYPE_REQUEST = 'FETCH_EVENT_TYPE_REQUEST';
export const FETCH_EVENT_TYPE_FAILURE = 'FETCH_EVENT_TYPE_FAILURE';

export const FETCH_NMOC_SUCCESS = 'FETCH_NMOC_SUCCESS';
export const FETCH_NMOC_REQUEST = 'FETCH_NMOC_REQUEST';
export const FETCH_NMOC_FAILURE = 'FETCH_NMOC_FAILURE';

export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS';
export const FETCH_EXERCISES_REQUEST = 'FETCH_EXERCISES_REQUEST';
export const FETCH_EXERCISES_FAILURE = 'FETCH_EXERCISES_FAILURE';

